apiVersion: 1

datasources:
  - name: SMSPlus-Postgres
    uid: smsplus-postgres
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: smsplus
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
